blank_issues_enabled: false

contact_links:

  - name: DevOps Cloud Services Program
    url: https://www.cronops.io
    about: |-
      DevOps Enablement Open Source Initiative. Open Source initiative to bring DevOps culture and software development best practices closer to the community.